# Generated by Django 2.2.12 on 2020-05-05 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0009_auto_20200429_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataQualityDashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chamber', models.CharField(max_length=20)),
                ('total_bills', models.PositiveIntegerField()),
                ('latest_bill_created_date', models.DateTimeField()),
                ('latest_action_date', models.DateTimeField()),
                ('earliest_action_date', models.DateTimeField()),
                ('average_sponsors_per_bill', models.PositiveIntegerField()),
                ('min_sponsors_per_bill', models.PositiveIntegerField()),
                ('max_sponsors_per_bill', models.PositiveIntegerField()),
                ('average_actions_per_bill', models.PositiveIntegerField()),
                ('min_actions_per_bill', models.PositiveIntegerField()),
                ('max_actions_per_bill', models.PositiveIntegerField()),
                ('average_votes_per_bill', models.PositiveIntegerField()),
                ('min_votes_per_bill', models.PositiveIntegerField()),
                ('max_votes_per_bill', models.PositiveIntegerField()),
                ('average_documents_per_bill', models.PositiveIntegerField()),
                ('min_documents_per_bill', models.PositiveIntegerField()),
                ('max_documents_per_bill', models.PositiveIntegerField()),
                ('average_versions_per_bill', models.PositiveIntegerField()),
                ('min_versions_per_bill', models.PositiveIntegerField()),
                ('max_versions_per_bill', models.PositiveIntegerField()),
                ('total_bills_no_sources', models.PositiveIntegerField()),
                ('total_votes_no_sources', models.PositiveIntegerField()),
                ('overall_number_of_subjects', models.PositiveIntegerField()),
                ('number_of_subjects_in_chamber', models.PositiveIntegerField()),
                ('number_of_bills_without_subjects', models.PositiveIntegerField()),
                ('total_bills_without_versions', models.PositiveIntegerField()),
                ('total_votes_without_voters', models.PositiveIntegerField()),
                ('total_votes_bad_counts', models.PositiveIntegerField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.LegislativeSession')),
            ],
        ),
    ]
