# Generated by Django 2.2.12 on 2020-06-12 20:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("dashboards", "0001_initial")]

    operations = [
        migrations.RemoveField(
            model_name="dataqualityreport", name="overall_number_of_subjects"
        )
    ]
