# Generated by Django 2.2.12 on 2020-07-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboards", "0002_remove_dataqualityreport_overall_number_of_subjects")
    ]

    operations = [
        migrations.AlterField(
            model_name="dataqualityreport",
            name="earliest_action_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="dataqualityreport",
            name="latest_action_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="dataqualityreport",
            name="latest_bill_created_date",
            field=models.DateTimeField(null=True),
        ),
    ]
