# Generated by Django 2.2.12 on 2020-04-01 21:26

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import profiles.models
import profiles.utils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("data", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=profiles.models._str_uuid,
                        editable=False,
                        max_length=22,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(editable=False, max_length=254)),
                ("sent", models.DateTimeField(editable=False)),
                ("num_query_updates", models.PositiveIntegerField(editable=False)),
                ("num_bill_updates", models.PositiveIntegerField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organization_name", models.CharField(blank=True, max_length=100)),
                ("about", models.TextField(blank=True)),
                ("feature_subscriptions", models.BooleanField(default=True)),
                ("subscription_emails_html", models.BooleanField(default=True)),
                (
                    "subscription_frequency",
                    models.CharField(
                        choices=[("d", "daily"), ("w", "weekly")],
                        default="w",
                        max_length=1,
                    ),
                ),
                (
                    "subscription_last_checked",
                    models.DateTimeField(default=profiles.utils.utcnow),
                ),
                ("api_key", models.CharField(default=uuid.uuid4, max_length=40)),
                (
                    "api_tier",
                    models.SlugField(
                        choices=[
                            ("inactive", "Not Yet Activated"),
                            ("suspended", "Suspended"),
                            ("default", "Default (new user)"),
                            ("bronze", "Bronze"),
                            ("silver", "Silver"),
                            ("unlimited", "Unlimited"),
                        ],
                        default="inactive",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("query", models.CharField(blank=True, max_length=300)),
                ("state", models.CharField(blank=True, max_length=2)),
                ("chamber", models.CharField(blank=True, max_length=15)),
                ("session", models.CharField(blank=True, max_length=100)),
                ("classification", models.CharField(blank=True, max_length=50)),
                (
                    "subjects",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        size=None,
                    ),
                ),
                (
                    "status",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        size=None,
                    ),
                ),
                (
                    "bill",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="data.Bill",
                    ),
                ),
                (
                    "sponsor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="data.Person",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UsageReport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("endpoint", models.CharField(max_length=100)),
                ("calls", models.PositiveIntegerField()),
                ("total_duration_seconds", models.PositiveIntegerField()),
                (
                    "profile",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_reports",
                        to="profiles.Profile",
                    ),
                ),
            ],
            options={
                "unique_together": {("profile", "date", "endpoint")},
            },
        ),
    ]
