# Generated by Django 2.2.14 on 2020-09-03 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["api_key"], name="profiles_pr_api_key_10054a_idx"
            ),
        ),
    ]
