# Generated by Django 2.2.3 on 2020-01-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("profiles", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="profile", name="about", field=models.TextField(blank=True)
        ),
        migrations.AlterField(
            model_name="profile",
            name="organization_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
