# Generated by Django 2.2.3 on 2020-01-21 19:53

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("legislative", "0009_searchablebill"),
        ("core", "0004_auto_20171005_2028"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("profiles", "0002_auto_20200121_1755"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("query", models.CharField(blank=True, max_length=300)),
                ("state", models.CharField(blank=True, max_length=2)),
                ("chamber", models.CharField(blank=True, max_length=15)),
                ("session", models.CharField(blank=True, max_length=100)),
                ("classification", models.CharField(blank=True, max_length=50)),
                (
                    "subjects",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100), size=None
                    ),
                ),
                (
                    "status",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50), size=None
                    ),
                ),
                (
                    "bill",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="legislative.Bill",
                    ),
                ),
                (
                    "sponsor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="core.Person",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
