# Generated by Django 2.2.3 on 2020-01-21 19:56

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("profiles", "0003_subscription")]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="bill",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to="legislative.Bill",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="sponsor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to="core.Person",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="status",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=50), blank=True, size=None
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="subjects",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100), blank=True, size=None
            ),
        ),
    ]
