# Generated by Django 2.2.3 on 2020-01-28 21:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("profiles", "0004_auto_20200121_1956")]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="subscription_frequency",
            field=models.CharField(
                choices=[("d", "daily"), ("w", "weekly")], default="w", max_length=1
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="subscription_last_checked",
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
    ]
