# Generated by Django 2.2.3 on 2020-01-29 20:23

from django.db import migrations, models
import profiles.utils


class Migration(migrations.Migration):

    dependencies = [("profiles", "0005_auto_20200128_2138")]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="subscription_last_checked",
            field=models.DateTimeField(default=profiles.utils.utcnow),
        )
    ]
