# Generated by Django 2.2.3 on 2020-01-29 23:20

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [("profiles", "0007_profile_subscription_emails_html")]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=profiles.models._str_uuid,
                        editable=False,
                        max_length=22,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(editable=False, max_length=254)),
                ("sent", models.DateTimeField(editable=False)),
                ("num_query_updates", models.PositiveIntegerField()),
                ("num_bill_updates", models.PositiveIntegerField()),
            ],
        )
    ]
