# Generated by Django 2.2.3 on 2020-01-30 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("profiles", "0008_notification")]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="num_bill_updates",
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name="notification",
            name="num_query_updates",
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
