# Generated by Django 2.2.3 on 2020-02-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("profiles", "0009_auto_20200130_0244")]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="feature_subscriptions",
            field=models.BooleanField(default=True),
        )
    ]
