# Generated by Django 2.2.10 on 2020-03-13 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("simplekeys", "0003_auto_20181030_0030"),
        ("profiles", "0010_auto_20200212_1645"),
    ]

    operations = [
        migrations.CreateModel(
            name="UsageReport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("endpoint", models.CharField(max_length=100)),
                ("calls", models.PositiveIntegerField()),
                ("total_duration_seconds", models.PositiveIntegerField()),
                (
                    "key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_reports",
                        to="simplekeys.Key",
                    ),
                ),
            ],
            options={"unique_together": {("key", "date", "endpoint")}},
        )
    ]
