# Generated by Django 2.2.10 on 2020-03-18 13:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    replaces = [
        ("profiles", "0011_usagereport"),
        ("profiles", "0012_auto_20200317_2102"),
        ("profiles", "0013_usagereport_profile"),
        ("profiles", "0014_auto_20200317_2359"),
        ("profiles", "0015_auto_20200318_0025"),
    ]

    dependencies = [("profiles", "0010_auto_20200212_1645")]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="api_key",
            field=models.CharField(default=uuid.uuid4, max_length=40),
        ),
        migrations.AddField(
            model_name="profile",
            name="api_tier",
            field=models.SlugField(
                choices=[
                    ("inactive", "Not Yet Activated"),
                    ("suspended", "Suspended"),
                    ("demo", "Demo"),
                    ("unlimited", "Unlimited"),
                    ("default", "Default (new user)"),
                    ("bronze", "Bronze"),
                    ("silver", "Silver"),
                ],
                default="inactive",
            ),
        ),
        migrations.CreateModel(
            name="UsageReport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("endpoint", models.CharField(max_length=100)),
                ("calls", models.PositiveIntegerField()),
                ("total_duration_seconds", models.PositiveIntegerField()),
                (
                    "profile",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_reports",
                        to="profiles.Profile",
                    ),
                ),
            ],
            options={"unique_together": {("profile", "date", "endpoint")}},
        ),
    ]
