# Generated by Django 2.2.10 on 2020-03-17 05:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [("profiles", "0011_usagereport")]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="api_key",
            field=models.CharField(default=uuid.uuid4, max_length=40, unique=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="api_tier",
            field=models.SlugField(
                choices=[
                    ("inactive", "Not Yet Activated"),
                    ("suspended", "Suspended"),
                    ("demo", "Demo"),
                    ("unlimited", "Unlimited"),
                    ("default", "Default (new user)"),
                    ("bronze", "Bronze"),
                    ("silver", "Silver"),
                ],
                default="inactive",
            ),
        ),
        migrations.AlterField(
            model_name="usagereport",
            name="key",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usage_reports",
                to="profiles.Profile",
            ),
        ),
    ]
