# Generated by Django 2.2.10 on 2020-03-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0012_auto_20200324_1446"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="api_tier",
            field=models.SlugField(
                choices=[
                    ("inactive", "Not Yet Activated"),
                    ("suspended", "Suspended"),
                    ("default", "Default (new user)"),
                    ("bronze", "Bronze"),
                    ("silver", "Silver"),
                    ("unlimited", "Unlimited"),
                ],
                default="inactive",
            ),
        ),
    ]
