# Generated by Django 2.2.10 on 2020-03-17 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("profiles", "0012_auto_20200317_2102")]

    operations = [
        migrations.AddField(
            model_name="usagereport",
            name="profile",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usage_reports",
                to="profiles.Profile",
                null=True,
            ),
        )
    ]
