# Generated by Django 2.2.10 on 2020-03-17 23:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [("profiles", "0013_usagereport_profile")]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="api_key",
            field=models.CharField(default=uuid.uuid4, max_length=40),
        )
    ]
