# Generated by Django 2.2.3 on 2020-01-15 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("bulk", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="dataexport",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        )
    ]
