# Generated by Django 2.2.3 on 2020-02-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("bulk", "0002_dataexport_updated_at")]

    operations = [
        migrations.AddField(
            model_name="dataexport",
            name="data_type",
            field=models.CharField(
                choices=[("csv", "csv"), ("json", "json")], default="csv", max_length=4
            ),
        )
    ]
