# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('admintools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unamtched_person_count', models.PositiveIntegerField(default=0)),
                ('no_memberships_count', models.PositiveIntegerField(default=0)),
                ('jurisdiction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_report', to='core.Jurisdiction')),
            ],
            options={
                'db_table': 'admintools_org_report',
            },
        ),
        migrations.CreateModel(
            name='PeopleReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('all_missing_count', models.PositiveIntegerField(default=0)),
                ('jurisdiction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people_report', to='core.Jurisdiction')),
            ],
            options={
                'db_table': 'admintools_people_report',
            },
        ),
        migrations.AlterField(
            model_name='dataqualityissue',
            name='issue',
            field=models.CharField(max_length=150),
        ),
    ]
