# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-02 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admintools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataqualityissues',
            name='reporter',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='dataqualityissues',
            name='object_id',
            field=models.CharField(max_length=300),
        ),
    ]
