# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admintools', '0002_auto_20170609_0055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peoplereport',
            name='all_missing_count',
        ),
        migrations.AddField(
            model_name='peoplereport',
            name='missing_address_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='peoplereport',
            name='missing_email_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='peoplereport',
            name='missing_phone_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='peoplereport',
            name='missing_photo_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
