# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-03 22:38
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admintools', '0002_auto_20170602_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataqualityissues',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='dataqualityissues',
            name='object_id',
        ),
        migrations.AddField(
            model_name='dataqualityissues',
            name='related_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='dataqualityissues',
            name='issue',
            field=models.CharField(choices=[('address', 'Missing Postal Address'), ('email', 'Missing Email'), ('voice', 'Missing Voice Phone'), ('image', 'Missing Photo URL'), ('org_no_memberships', 'Organization with no memberships'), ('unmatched_org_person', 'Organization with unmatched person'), ('voteevent_missing_bill', 'Vote Events with no associated bills'), ('unmatched_voter', 'Vote Event which has unmatched voter'), ('missing_voters', 'Vote Event without any voters'), ('missing_votes', 'Vote Event without yes & no vote counts'), ('bad_votes', 'Vote Event with bad vote count'), ('no_actions', 'Bill with no action'), ('no_sponsors', 'Bill with no sponsor'), ('unmatched_person_sponsor', 'Bill has sponsor with unmatched person'), ('no_versions', 'Bill with no version'), ('unmatched_org_sponsor', 'Bill has sponsor with unmatched organization')], max_length=50),
        ),
    ]
