# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 08:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admintools', '0003_auto_20170609_0137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizationreport',
            old_name='unamtched_person_count',
            new_name='unmatched_person_count',
        ),
    ]
