# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admintools', '0003_auto_20170714_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issueresolverpatch',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('unreviewed', 'Unreviewed'), ('deprecated', 'Deprecated'), ('rejected', 'Rejected')], max_length=100),
        ),
    ]
