# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admintools', '0004_auto_20170717_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataqualityissue',
            name='issue',
            field=models.CharField(choices=[('missing-phone', 'Missing Phone Number'), ('missing-email', 'Missing Email'), ('missing-address', 'Missing Postal Address'), ('missing-photo', 'Missing Photo'), ('no-memberships', 'No Memberships'), ('unmatched-person', 'Unmatched Person'), ('many-memberships', 'Too Many People'), ('few-memberships', 'Too Few people'), ('no-actions', 'Missing Actions'), ('no-sponsors', 'Missing Sponsors'), ('no-versions', 'Missing Versions'), ('unmatched-person-sponsor', 'Sponsor With Unmatched Person'), ('unmatched-org-sponsor', 'Sponsor With Unmatched Organization'), ('missing-bill', 'Missing Bill'), ('missing-voters', 'Missing Voters'), ('missing-counts', 'Missing Counts'), ('bad-counts', 'Bad Counts'), ('unmatched-voter', 'Unmatched Voter')], max_length=150),
        ),
    ]
