# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 20:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('admintools', '0005_auto_20170609_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('no_actions_count', models.PositiveIntegerField(default=0)),
                ('no_sponsors_count', models.PositiveIntegerField(default=0)),
                ('no_versions_count', models.PositiveIntegerField(default=0)),
                ('unmatched_person_sponsor_count', models.PositiveIntegerField(default=0)),
                ('unmatched_org_sponsor_count', models.PositiveIntegerField(default=0)),
                ('jurisdiction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_report', to='core.Jurisdiction')),
            ],
            options={
                'db_table': 'admintools_bill_report',
            },
        ),
        migrations.CreateModel(
            name='VoteEventReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('missing_bill_count', models.PositiveIntegerField(default=0)),
                ('missing_voters_count', models.PositiveIntegerField(default=0)),
                ('missing_counts_count', models.PositiveIntegerField(default=0)),
                ('bad_counts_count', models.PositiveIntegerField(default=0)),
                ('unmatched_voter_count', models.PositiveIntegerField(default=0)),
                ('jurisdiction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voteevent_report', to='core.Jurisdiction')),
            ],
            options={
                'db_table': 'admintools_voteevent_report',
            },
        ),
    ]
