# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-10 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admintools', '0006_dataqualityissue_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataqualityissue',
            name='message',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
