# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 21:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admintools', '0006_billreport_voteeventreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billreport',
            name='jurisdiction',
        ),
        migrations.RemoveField(
            model_name='organizationreport',
            name='jurisdiction',
        ),
        migrations.RemoveField(
            model_name='peoplereport',
            name='jurisdiction',
        ),
        migrations.RemoveField(
            model_name='voteeventreport',
            name='jurisdiction',
        ),
        migrations.DeleteModel(
            name='BillReport',
        ),
        migrations.DeleteModel(
            name='OrganizationReport',
        ),
        migrations.DeleteModel(
            name='PeopleReport',
        ),
        migrations.DeleteModel(
            name='VoteEventReport',
        ),
    ]
