# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-15 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admintools', '0007_dataqualityissue_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataqualityissue',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
