# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataquality', '0002_issueresolverpatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issueresolverpatch',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('unreviewed', 'Unreviewed'), ('deprecated', 'Deprecated')], max_length=100),
        ),
    ]
