# Generated by Django 2.0 on 2018-02-19 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataquality', '0008_auto_20170815_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issueresolverpatch',
            name='alert',
        ),
        migrations.AlterIndexTogether(
            name='dataqualityissue',
            index_together=set(),
        ),
        migrations.RemoveField(
            model_name='dataqualityissue',
            name='alert',
        ),
    ]
