# Generated by Django 2.0 on 2018-02-20 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataquality', '0009_auto_20180219_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataqualityissue',
            name='reporter',
        ),
        migrations.AddField(
            model_name='dataqualityissue',
            name='unmatched_name',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='dataqualityissue',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
