# Generated by Django 2.2.3 on 2020-02-10 20:01

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BillHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_time", models.DateTimeField(editable=False)),
                ("table_name", models.CharField(max_length=100)),
                ("bill_id", models.CharField(max_length=45)),
                ("old", django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ("new", django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
        )
    ]
