# Generated by Django 3.1.2 on 2020-10-05 22:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("widgets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="widgetconfig",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="widgetconfig",
            name="name",
            field=models.TextField(
                default=datetime.datetime(2020, 10, 5, 22, 1, 57, 581611), max_length=50
            ),
            preserve_default=False,
        ),
    ]
