# Generated by Django 2.2.12 on 2020-04-01 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [("data", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="BillStatus",
            fields=[
                (
                    "bill",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="data.Bill",
                    ),
                ),
                ("first_action_date", models.CharField(max_length=25)),
                ("latest_action_date", models.CharField(max_length=25)),
                ("latest_action_description", models.TextField()),
                ("latest_passage_date", models.CharField(max_length=25)),
            ],
            options={"managed": False},
        ),
        migrations.CreateModel(
            name="OrganizationProxy",
            fields=[],
            options={"proxy": True, "indexes": [], "constraints": []},
            bases=("data.organization",),
        ),
        migrations.CreateModel(
            name="PersonProxy",
            fields=[],
            options={"proxy": True, "indexes": [], "constraints": []},
            bases=("data.person",),
        ),
        migrations.RunSQL(
            """
           CREATE MATERIALIZED VIEW public_billstatus AS
           SELECT b.id as bill_id,
           (SELECT MIN(date) from opencivicdata_billaction WHERE bill_id = b.id) as "first_action_date",
           (SELECT MAX(date) from opencivicdata_billaction WHERE bill_id = b.id) as "latest_action_date",
           (SELECT MAX(date) from opencivicdata_billaction WHERE bill_id = b.id and classification @> ARRAY['passage']) as "latest_passage_date",
           (SELECT description from opencivicdata_billaction WHERE bill_id = b.id ORDER by date DESC LIMIT 1) as "latest_action_description"
           FROM opencivicdata_bill b;
           CREATE UNIQUE INDEX public_billstatus_pk ON public_billstatus(bill_id);
           """,
            """
           DROP MATERIALIZED VIEW public_billstatus
           """,
        ),
    ]
