# Generated by Django 2.2.12 on 2020-04-22 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("public", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="OrganizationProxy",),
        migrations.DeleteModel(name="PersonProxy",),
    ]
