# Generated by Django 2.0.9 on 2018-12-29 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("legislative", "0008_longer_event_name"),
        ("public", "0002_organizationproxy"),
    ]

    operations = [
        migrations.CreateModel(
            name="BillStatus",
            fields=[
                (
                    "bill",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="legislative.Bill",
                    ),
                ),
                ("first_action_date", models.CharField(max_length=25)),
                ("latest_action_date", models.CharField(max_length=25)),
                ("latest_action_description", models.TextField()),
                ("latest_passage_date", models.CharField(max_length=25)),
            ],
            options={"managed": False},
        ),
        migrations.RunSQL(
            """
           CREATE MATERIALIZED VIEW public_billstatus AS
           SELECT b.id as bill_id,
           (SELECT MIN(date) from opencivicdata_billaction WHERE bill_id = b.id) as "first_action_date",
           (SELECT MAX(date) from opencivicdata_billaction WHERE bill_id = b.id) as "latest_action_date",
           (SELECT MAX(date) from opencivicdata_billaction WHERE bill_id = b.id and classification @> ARRAY['passage']) as "latest_passage_date",
           (SELECT description from opencivicdata_billaction WHERE bill_id = b.id ORDER by date ASC LIMIT 1) as "latest_action_description"
           FROM opencivicdata_bill b;
           CREATE UNIQUE INDEX public_billstatus_pk ON public_billstatus(bill_id);
           """,
            """
           DROP MATERIALIZED VIEW public_billstatus
           """,
        ),
    ]
