# Generated by Django 2.2.12 on 2020-04-01 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("boundaries", "0007_auto_20180325_1421"),
        ("data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DivisionGeometry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "boundary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="geometries",
                        to="boundaries.Boundary",
                    ),
                ),
                (
                    "division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="geometries",
                        to="data.Division",
                    ),
                ),
            ],
        ),
    ]
