# Generated by Django 2.0 on 2018-06-23 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_auto_20171005_2028'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrowdSourceIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=300)),
                ('issue', models.CharField(choices=[('missing-phone', 'Missing Phone Number'), ('missing-email', 'Missing Email'), ('missing-address', 'Missing Postal Address'), ('missing-photo', 'Missing Photo'), ('no-memberships', 'No Memberships'), ('unmatched-person', 'Unmatched Person'), ('many-memberships', 'Too Many People'), ('few-memberships', 'Too Few people'), ('no-actions', 'Missing Actions'), ('no-sponsors', 'Missing Sponsors'), ('no-versions', 'Missing Versions'), ('unmatched-person-sponsor', 'Sponsor With Unmatched Person'), ('unmatched-org-sponsor', 'Sponsor With Unmatched Organization'), ('missing-bill', 'Missing Bill'), ('missing-voters', 'Missing Voters'), ('missing-counts', 'Missing Counts'), ('bad-counts', 'Bad Counts'), ('unmatched-voter', 'Unmatched Voter'), ('wrong-phone', 'Wrong Phone Number'), ('wrong-email', 'Wrong Email'), ('wrong-address', 'Wrong Postal Address'), ('wrong-photo', 'Wrong Photo')], max_length=150)),
                ('status', models.CharField(choices=[('active', 'Active'), ('ignored', 'Ignored')], default='active', max_length=10)),
                ('message', models.TextField(blank=True)),
                ('reporter_email', models.EmailField(blank=True, max_length=254)),
                ('reporter_name', models.CharField(blank=True, max_length=500)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('jurisdiction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crowdsource_issues', to='core.Jurisdiction')),
            ],
        ),
    ]
