# Generated by Django 2.0 on 2018-06-25 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crowdsource', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrowdSourceIssueResolver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('unreviewed', 'Unreviewed'), ('deprecated', 'Deprecated'), ('rejected', 'Rejected')], default='unreviewed', max_length=100)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField()),
                ('note', models.TextField(blank=True)),
                ('source', models.URLField(blank=True, max_length=2250)),
                ('reporter_email', models.EmailField(blank=True, max_length=254)),
                ('reporter_name', models.CharField(blank=True, max_length=500)),
                ('applied_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crowdsource.CrowdSourceIssue')),
            ],
        ),
    ]
