# Generated by Django 2.0 on 2018-06-25 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsource', '0002_crowdsourceissueresolver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crowdsourceissueresolver',
            name='applied_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
