# Generated by Django 2.2.12 on 2020-04-01 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LegacyBillMapping",
            fields=[
                (
                    "legacy_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                (
                    "bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="legacy_mapping",
                        to="data.Bill",
                    ),
                ),
            ],
        ),
    ]
