# Generated by Django 2.0.9 on 2018-10-28 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [("legislative", "0006_billversion_extras")]

    operations = [
        migrations.CreateModel(
            name="LegacyBillMapping",
            fields=[
                (
                    "legacy_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                (
                    "bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="legacy_mapping",
                        to="legislative.Bill",
                    ),
                ),
            ],
        )
    ]
