# Generated by Django 2.2.16 on 2021-02-25 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("data", "0028_auto_20201022_1642"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnmatchedName",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("sponsorships_count", models.PositiveIntegerField()),
                ("votes_count", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("U", "Unmatched"),
                            ("P", "Matched Person"),
                            ("E", "Source Error"),
                            ("I", "Ignored"),
                        ],
                        default="U",
                        max_length=1,
                    ),
                ),
                (
                    "matched_person",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="data.Person",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data.LegislativeSession",
                    ),
                ),
            ],
        ),
    ]
