# Generated by Django 3.1.7 on 2021-04-01 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("people_admin", "0004_auto_20210331_1735"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="persondelta",
            options={
                "permissions": [
                    ("can_edit", "Can edit people."),
                    ("can_retire", "Can retire people."),
                ]
            },
        ),
    ]
